name: Check linting, test and vitals

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  suite:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup and run Cypress
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          start: npm start

      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier
        run: npm run format:check

      - name: Run Jest
        run: npm run test:unit

      - name: Push the coverage
        run: npm run coverage:push -- --token=${{ secrets.CODECOV_TOKEN }}
